swagger: "2.0"
info:
  title: mobile API
  description: |
    mobile has every tool to get any job done, so codename for the new mobile APIs.
  version: 1.0.0
  contact:
    email: astaxie@gmail.com
basePath: /object
paths: {}
definitions:
  models.Object:
    title: Object
    type: object
    properties:
      object_id:
        type: string
      player_name:
        type: string
      score:
        type: integer
        format: int64
