swagger: "2.0"
info:
  title: Object API Example
  description: |
    an example of CRUD operations with object apis.
  version: 1.0.0
basePath: /object
paths: {}
definitions:
  models.Object:
    title: Object
    type: object
    properties:
      object_id:
        type: string
      player_name:
        type: string
      score:
        type: integer
        format: int64
